Test steps for HTTP(S) responses

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -47,19 +47,27 @@ jobs:
         sudo cp ./apache/ssl/certs/lamp.localhost-rootCA.crt /usr/local/share/ca-certificates/lamp.localhost-rootCA.crt
         sudo update-ca-certificates
 
+    # - name: Test HTTP Response
+    #   run: |
+    #     curl -sS -f -D - http://localhost:80/ | egrep "Apache2 Ubuntu Default Page" > /dev/null || {
+    #       echo "[ERROR] Apache delivers unexpected content.";
+    #       exit 1
+    #     }
+
+    # - name: Test HTTPS Response
+    #   run: |
+    #     curl -sS -f -D - https://examplehost.lamp.localhost:443/ | egrep "https://www.php.net/" > /dev/null || {
+    #       echo "[ERROR] Apache delivers unexpected content.";
+    #       exit 1
+    #     }
+
     - name: Test HTTP Response
       run: |
-        curl -sS -f -D - http://localhost:80/ | egrep "Apache2 Ubuntu Default Page" > /dev/null || {
-          echo "[ERROR] Apache delivers unexpected content.";
-          exit 1
-        }
+        curl -sS -f -D - http://localhost:80/
 
     - name: Test HTTPS Response
       run: |
-        curl -sS -f -D - https://examplehost.lamp.localhost:443/ | egrep "https://www.php.net/" > /dev/null || {
-          echo "[ERROR] Apache delivers unexpected content.";
-          exit 1
-        }
+        curl -sS -f -D - https://examplehost.lamp.localhost:443/
 
     - name: Shutdown LAMP Stack
       if: always()
